config/routes.rb
Rails.application.routes.draw do

  get 'watson/update'
  resources :leads
  resources :quotes
  resources :interventions

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  authenticate :user, ->(user) { user.admin? || user.employee? } do
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :users

  scope '/admin' do
    resources :users
  end

  root :to => "main#index"

  get "/", to: "main#index"
  get "/index", to: "main#index"
  get "/residential", to: "main#residential"
  get "/commercial", to: "main#commercial"
  get "/new", to: "registrations#new"
  get "/interventions", to: "interventions#index"

  get 'get_buildings/', to: 'interventions#get_buildings'  
  get 'get_batteries/', to: 'interventions#get_batteries'  
  get 'get_columns/', to: 'interventions#get_columns'  
  get 'get_elevators/', to: 'interventions#get_elevators'  


  get '/speaker', to: 'main#speaker'
  get '/speechToText', to: 'main#stt'
  post '/speechToText/speechConverter', to: "main#speechConverter"
  post "/speaker/identifySpeaker", to: "main#identifySpeaker"
  # get "test", to: "test#index"
  # get "test2", to: "test#test2"
  # post "test2", to: "media#getContent"
  # post 'form_path', to: 'media#getContent'

  get '/react/weather', to: 'elevator_media#react'
  get '/getWeatherReact', to: 'elevator_media#getWeatherReact'

  get '/elevator_media', to: 'elevator_media#index'
  post '/elevator_media', to: 'elevator_media#getWeather'
  get '/getWeather', to: 'elevator_media#getWeather'
  get '/getJoke', to: 'elevator_media#getJoke'
  get '/getGif', to: 'elevator_media#getGif'
  get '/getAdvice', to: 'elevator_media#getAdvice'
  get '/getProgJoke', to: 'elevator_media#getProgJoke'
  get '/getDarkJoke', to: 'elevator_media#getDarkJoke'

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user, optional: true

  TYPE_LIST = [["Select Building Type"," "],["Residential","residential"], ["Commercial","commercial"], ["Corporate","corporate"], ["Hybrid","hybrid"]]
  PRODUCT = [["Standard", "standard"],["Premium","premium"],["Excelium", "excelium"]]
end

app/controllers/quotes_controller.rb
require 'zendesk_api'
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
    @quotesList = Quote.where(user_id: current_user.id)
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    if(quote_params[:email].present?)
      @quote = Quote.new(quote_params)
      @quote.save!
    else
      @quote = Quote.new(quote_params)
      @quote.user_id = current_user.id
      @quote.email = current_user.email
      @quote.save!
    end
    respond_to do |format|
      if @quote
        # createTicket()
        format.html { redirect_to "/", notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def createTicket()
    client = ZendeskAPI::Client.new do |config|
        config.url = ENV['ZENDESK_URL']
        config.username = ENV['ZENDESK_EMAIL']
        config.token = ENV['ZENDESK_API']
      end

      ZendeskAPI::Ticket.create!(client,
        :subject => "#{@quote.name} from #{@quote.company_name}",
        :comment => { :value =>
          "#{@quote.name} from company #{@quote.company_name} can be reached at the following email: #{@quote.email}.
          The quote contained the following informations:
          Building type: #{@quote.building_type}
          Amount of apartments: #{@quote.number_of_apartments}, Amount of floors: #{@quote.number_of_floors}, Amount of basements: #{@quote.number_of_basements},
          Amount of companies: #{@quote.number_of_companies}, Amount of parking spots: #{@quote.number_of_parking_spots}, Amount of elevators: #{@quote.number_of_elevators},
          Amount of corporations: #{@quote.number_of_corporations}, Maximum occupancy: #{@quote.maximum_occupancy},
          Product line: #{@quote.product_line}
          Total price of the elevators: #{@quote.elevator_total_price}
          Total price of the installation: #{@quote.installation_price}
          Total price: #{@quote.total_price}"},
        :type => "task",
        :priority => "normal")
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: "quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name,:building_type,:product_line,:elevator_unit_price,:elevator_total_price,:installation_price,:total_price,:company_name,:number_of_apartments,:number_of_floors,:number_of_basements,:number_of_companies,:number_of_parking_spots,:number_of_elevators,:number_of_corporations,:maximum_occupancy,:business_hours,:email)
    end


end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<div id="wrapper">

  <section class="page-header dark">
    <div class="container text-center">
      <h1 class="fw-800 fs-60 font-latoo">Request A Quote</h1>
    </div>
  </section>
  <!-- /PAGE HEADER -->



  <section class="dark">

  <%= simple_form_for(@quote) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="container">
    <div class="form-container">
      <div class="grid1">
                <%= f.input :name%><br/>
                <% if !user_signed_in? %>
                  <%= f.input :email%><br/>
                <% end %>
                <%= f.input :company_name, :label=>"Enter Your Company Name (optional)" %> <br/>
                <%= f.select :building_type, Quote::TYPE_LIST, :label=>"Select Your Building Type"%><br/>
        </div>



      <div class="grid2">
            <div class="">
                <div id="lineSelection" class="">
                  <%= f.input :product_line, :label=>"Select Your Product Line", as: :radio_buttons, collection: Quote::PRODUCT, wrapper: :vertical_collection_inline %>
      </div>
                  <script>//On product line click calc price
                    $('#lineSelection input[type=radio]').change(function () {
                      price($('#lineSelection input[type=radio]:checked').val());
                    });
                  </script>
      </div>
          <!--Questions-->
          <div id="questionInput">
                <div id="number_of_apartments" class="hidden">
                  <%= f.input :number_of_apartments, min: 0, class:"form-control" %>
              </div>

              <div id="number_of_floors" class="hidden">

                  <%= f.input :number_of_floors, min: 0, class:"form-control" %>

              </div>

              <div id="number_of_basements" class="hidden">

                  <%= f.input :number_of_basements, min: 0, class:"form-control" %>

              </div>

              <div id="number_of_companies" class="hidden">

                  <%= f.input :number_of_companies, min: 0, class:"form-control" %>

              </div>

              <div id="number_of_parking_spots" class="hidden">

                  <%= f.input :number_of_parking_spots, min: 0, class:"form-control" %>

              </div>

              <div id="number_of_elevators" class="hidden">

                  <%= f.input :number_of_elevators, min: 0, class:"form-control" %>

              </div>

              <div id="number_of_corporations" class="hidden">

                  <%= f.input :number_of_corporations, min: 0, class:"form-control" %>

              </div>

              <div id="maximum_occupancy" class="hidden">

                  <%= f.input :maximum_occupancy, min: 0, class:"form-control" %>

              </div>

              <div id="business_hours" class="hidden">

                  <%= f.input :business_hours, in: 1.0..24.0, class:"form-control" %>

              </div>
                </div>

        </div>

        <div>


    <form> <!--Estimated Elevators Form-->
      <div id="elevator-amount" class="fancy-form ">
        <label for="estimatedElevators" class="text-center">Number Of Elevators&nbsp;</label>
        <input readonly id="estimatedElevators" class="form-control" value="">
      </div>
    </form>




<!--Price Estimate Forms-->
          <div class="">
            <div id="elevator-unit-price" class="fancy-form ">
                        <%= f.input :elevator_unit_price, class:"form-control", :readonly=>true %><br/>
            </div>

            <div id="elevator-total-price" class="fancy-form ">
                      <%= f.input :elevator_total_price, class:"form-control", :readonly=>true %><br/>
            </div>

            <div id="installation-fees" class="fancy-form ">
                      <%= f.input :installation_price, class:"form-control", :readonly=>true %><br/>
            </div>

            <div id="final-price" class="fancy-form ">
                      <%= f.input :total_price, class:"form-control", :readonly=>true %><br/>
            </div>
            </div>

        </div>
      <div class="grid4">
      </div>

      <div class="text-center grid5">
        <% if user_signed_in? %>
          <div class="">
                <%= f.button :submit %>
          </div>
          Signed in as <%= current_user.email %>.
        <%= link_to "Edit profile", edit_user_registration_path %><br/> Not you?
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              <% else %>
                      <div>
                        <%= f.button :submit %>
                      </div>
                      <%= link_to "Sign up", new_user_registration_path %> or
                      <%= link_to "sign in", new_user_session_path %>
              <% end %>
          <% end %>
             <div>
                <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, id: "flash_#{name}" %>
              </div>
            </div>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/quotes/edit.html.erb
<script>
    $('document').ready(function () {
      $("select").change(function () {
        getBuildingType();
      });
    });
</script>

<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<script>

   $("#questionInput :input").bind(
    "keypress keydown keyup change onblur",
    function () {
      if (parseFloat($(':input[id="quote_business_hours"]').val(), 10) > 24) {
        $("#quote_business_hours").val(24);
      };
      switch (type) {
        case "residential":
          var apts = parseFloat($(':input[id="quote_number_of_apartments"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10);
          if (!isNaN(apts) && !isNaN(floors)) {
            calcResidential(apts, floors);
          }
          break;

        case "commercial":
          var
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            companies = parseFloat($(':input[id="quote_number_of_companies"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10),
            elevators = parseFloat($(':input[id="quote_number_of_elevators"]').val(),10);
          if (
            !isNaN(elevators)
          ) {
            $("#estimatedElevators").val(elevators);
          }
          break;

        case "corporate":
          var maxOccupancy = parseFloat($(':input[id="quote_maximum_occupancy"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            corporations = parseFloat($(':input[id="quote_number_of_corporation"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10);
          if (
            !isNaN(maxOccupancy) &&
            !isNaN(floors) &&
            !isNaN(basements)
          ) {
            calcCorpoHybrid(maxOccupancy, floors, basements);
          }
          break;

        case "hybrid":
          var maxOccupancy = parseFloat($(':input[id="quote_maximum_occupancy"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            companies = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            businessHours = parseFloat($(':input[id="quote_business_hours"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10);
          if (
            !isNaN(maxOccupancy) &&
            !isNaN(floors) &&
            !isNaN(basements)
          ) {
            calcCorpoHybrid(maxOccupancy, floors, basements);
          }
          break;
        default: hideQuestions();
          break;
      }

      price($("#lineSelection input[type=radio]:checked").val());
    }
  );

</script>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<section class="dark">
<p id="notice"><%= notice %></p>
  <div class="container">

    <h1 class="fw-800 fs-60 font-roboto" style="text-align: center">Quotes</h1>
    <table class="table table-hover table-bordered" style="width: 35%; margin: auto; padding: 10px; font-size: 18px>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody style="font-size: 18px">
        <% @quotesList.each do |quote| %>
          <tr style="">

            <td style=""><%= quote.name %></td>
            <td>
            <i class="fa fa-eye"></i>
            <%= link_to 'Show', quote %>
            <i class="fa fa-edit"></i>
            <%= link_to 'Edit', edit_quote_path(quote) %>
            <i class="fa fa-trash"></i>
            <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>

    <div style="margin: auto; padding: 10px; font-size: 18px; text-align: center">
      <%= link_to 'New Quote', new_quote_path %>
    </div>
  </div>
</section>

app/views/quotes/new.html.erb
<script>
    $('document').ready(function () {
      $("select").change(function () {
        getBuildingType();
      });
    });
</script>


<%= render 'form', quote: @quote %>


<script>

   $("#questionInput :input").bind(
    "keypress keydown keyup change onblur",
    function () {
      if (parseFloat($(':input[id="quote_business_hours"]').val(), 10) > 24) {
        $("#quote_business_hours").val(24);
      };
      switch (type) {
        case "residential":
          var apts = parseFloat($(':input[id="quote_number_of_apartments"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10);
          if (!isNaN(apts) && !isNaN(floors)) {
            calcResidential(apts, floors);
          }
          break;

        case "commercial":
          var
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            companies = parseFloat($(':input[id="quote_number_of_companies"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10),
            elevators = parseFloat($(':input[id="quote_number_of_elevators"]').val(),10);
          if (
            !isNaN(elevators)
          ) {
            $("#estimatedElevators").val(elevators);
          }
          break;

        case "corporate":
          var maxOccupancy = parseFloat($(':input[id="quote_maximum_occupancy"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            corporations = parseFloat($(':input[id="quote_number_of_corporation"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10);
          if (
            !isNaN(maxOccupancy) &&
            !isNaN(floors) &&
            !isNaN(basements)
          ) {
            calcCorpoHybrid(maxOccupancy, floors, basements);
          }
          break;

        case "hybrid":
          var maxOccupancy = parseFloat($(':input[id="quote_maximum_occupancy"]').val(),10),
            floors = parseFloat($(':input[id="quote_number_of_floors"]').val(),10),
            basements = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            companies = parseFloat($(':input[id="quote_number_of_basements"]').val(),10),
            businessHours = parseFloat($(':input[id="quote_business_hours"]').val(),10),
            parkingSpots = parseFloat($(':input[id="quote_number_of_parking_spots"]').val(),10);
          if (
            !isNaN(maxOccupancy) &&
            !isNaN(floors) &&
            !isNaN(basements)
          ) {
            calcCorpoHybrid(maxOccupancy, floors, basements);
          }
          break;
        default: hideQuestions();
          break;
      }

      price($("#lineSelection input[type=radio]:checked").val());
    }
  );

</script>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<section class="dark">

<p id="notice"><%= notice %></p>

<p style="margin: auto; padding: 10px; font-size: 48px, text-align: center">
  <strong>Name:</strong>
  <%= @quote.name %><br/>
  <strong>Total Price:</strong>
  <%= @quote.total_price %><br/>
</p>
<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>
</section>